### ISSUE TITLE
Not work Dynamic Size for Font

### ISSUE THREAD

**Issue by AlexeyGorbunov** [gonzalezreal/AttributedText#11]
Good afternoon!
Thanks for your library, it helped a lot in development. But I noticed that if you change the font size in the application, AttibutedText will not change size, to fix this you need to add this line:

`textView.adjustsFontForContentSizeCategory = true`

**Comment by gonzalezreal** [comment]
Hi,
Thanks for the feedback! I will have a look at this as soon as I can.
